### ISSUE TITLE
Install script not working - Failed to download template from registry

### ISSUE THREAD

**Issue by jarle** [adonisjs/web-starter-kit#10]
### Package version

n/a

### Describe the bug

I run the start script `npm init adonisjs -- -K=web`

That gives the following error:
```
❯ Where should we create the project? · ./my-adonisjs-app
[ wait ] Failed to download template ...
[ error ] Failed to download template from registry: Failed to download web template info from https://raw.githubusercontent.com/unjs/giget/main/templates/web.json: 404 Not Found
```

**Comment by Julien-R44** [comment]
Strange it works fine for me. Can you try with `npm init adonisjs@latest -- -K=web` instead ? 

What if you do not pass the `-K` argument and instead select the template from the prompt ?

**Comment by jarle** [comment]
Both of the commands you suggested worked for me:
- `npm init adonisjs@latest -- -K=web`
- `npm init adonisjs --`

The original command was copied from the readme and still gives the same error for me.

**Comment by RomainLanz** [comment]
The readme has to be updated, we must use `@latest` to ensure loading the latest version of the script.

**Comment by Julien-R44** [comment]
Updated the readme
