### ISSUE TITLE
Statuspages not working from the get-go

### ISSUE THREAD

**Issue by MichaelBelgium** [adonisjs/web-starter-kit#4]
### Package version

latest

### Describe the bug

Perhaps not really a bug but when scaffolding the web starter kit, the statuspages don't work from the get-go - it can't find the custom error pages at first

https://github.com/adonisjs/web-starter-kit/blob/eb393593f19399dceb3ddf51799322be4e1cb50f/app/exceptions/handler.ts#L23-L30

The errors templates are in the folder pages/errors and not errors/

So should be changed to

```ts
return view.render('pages/errors/not-found', { error })
```

or move the errors folder up a level :)

**Comment by Julien-R44** [comment]
Nice catch
Fixed here https://github.com/adonisjs/web-starter-kit/commit/67a87f46d55c26ee9ce2deeb593744d84ac09f83
